In [6]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [16]:
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in range(10000)]
end_time=process_time()
print(end_time-start_time)

0.0


In [23]:
from time import process_time
a=np.array([i for i in range(10000)])
start_time=process_time()
a=a+5
end_time=process_time()
print(end_time-start_time)

0.0


In [51]:
a=np.array([(1,2,3),(5,6,7)])
print(a.itemsize)

4


In [29]:
a=np.array([(1,2,3),(4,5,6)])
print(a.dtype)

int32


In [30]:
a=np.array([(1,2,3),(4,5,8)])
print(a.size)
print(a.shape)


6
(2, 3)


In [31]:
a=np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)


[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [13]:
a=np.array([(1,2,3,4),(8,9,10,11)])
print(a[1,3])


11


In [38]:
a=np.array([(1,2,3,4),(8,9,10,11),(12,13,14,15)])
print(a[0:,0])

[ 1  8 12]


In [49]:
a=np.array([(1,2,3,4),(8,9,10,11),(12,13,14,15),(16,17,18,19)])
print(a[0:3,1]) 


[ 2  9 13]


In [ ]:

a=np.linspace(10,20,4)
print(a)



[10.         13.33333333 16.66666667 20.        ]


In [ ]:

a=np.arange(7,20,4)
print(a)

[ 7 11 15 19]


In [ ]:
a=np.array([1,2,3])
print(a.min())


1


In [ ]:

a=np.array([(1,2,3),(5,6,7)])
print(a.sum(axis=1))


[ 6 18]


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
print(np.sqrt(a))


[[2.82842712 3.         3.16227766]
 [3.31662479 3.60555128 3.87298335]]


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
print(np.std(a))

2.3804761428476167


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
print(np.mean(a))

11.0


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
print(np.cov(a))

[[1. 2.]
 [2. 4.]]


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
b=np.array([(4,5,6),(8,10,12)])
print(a+b)
print(a-b)
print(a*b)


[[12 14 16]
 [19 23 27]]
[[4 4 4]
 [3 3 3]]
[[ 32  45  60]
 [ 88 130 180]]


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
b=np.array([(4,5,6),(8,10,12)])
print(np.vstack((a,b)))

[[ 8  9 10]
 [11 13 15]
 [ 4  5  6]
 [ 8 10 12]]


In [ ]:
a=np.array([(8,9,10),(11,13,15)])
b=np.array([(4,5,6),(8,10,12)])
print(np.hstack((a,b)))

[[ 8  9 10  4  5  6]
 [11 13 15  8 10 12]]
